repos:
  - repo: local
    hooks:
      - id: poetry-lock
        name: Poetry Lock
        entry: poetry lock
        language: system
        files: pyproject.toml
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        # language: system
        pass_filenames: false
        args: ["."]
        additional_dependencies:
          - "pydantic>=2.7"
          - "wandb"
