version: 2.1

jobs:
  tests:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install dependencies
          command: uv sync --extra test
      - run:
          name: Run tests
          command: uv run pytest --cov
      - run:
          name: Manually upload coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t $CODECOV_TOKEN -f coverage.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - tests:
          matrix:
            parameters:
              python-version: ["3.9", "3.10", "3.11", "3.12"]
