version: 2.1

jobs:
  tests:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Set up Poetry environment
          command: |
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install dependencies
          command: poetry install -E test -vvv
      - run:
          name: Run tests
          command: poetry run pytest
      - run:
          name: Run examples
          command: |
            find examples/ -name "*.py" -print | while read script; do
              echo "Running $script"
              poetry run python "$script" || exit 1  # Exit on any error
            done

      # TODO: Configure Codecov for wandb-workspaces
      # - run:
      #     name: Upload coverage to Codecov
      #     command: |
      #       curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN} -f coverage.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - tests:
          matrix:
            parameters:
              python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
