version: 2.1

jobs:
  tests:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Set up Poetry environment
          command: |
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install dependencies
          command: poetry install -E test -vvv
      - run:
          name: Run tests
          command: poetry run pytest --cov
      - run:
          name: Run examples
          command: |
            find examples/ -name "*.py" -print | while read -r script; do
              echo "Running $script"
              coverage_file=".coverage_$(basename $script .py)"
              poetry run coverage run --source=wandb_workspaces --data-file="$coverage_file" "$script"
              if [ $? -ne 0 ]; then
                echo "Script $script failed. Exiting."
                exit 1
              fi
            done
      - run:
          name: Combine coverage reports
          command: poetry run coverage combine .coverage*
      - run:
          name: Report coverage
          command: poetry run coverage xml
      - run:
          name: Manually upload coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t $CODECOV_TOKEN -f coverage.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - tests:
          matrix:
            parameters:
              python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
