name: Release and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.2.0)'
        required: true
        type: string
      dry_run:
        description: 'Dry run (skip PyPI publish)'
        required: false
        type: boolean
        default: false

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      branch_name: ${{ steps.create_branch.outputs.branch_name }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.11'
          
      - name: Setup git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Install toml
        run: pip install toml
      
      - name: Create release branch
        id: create_branch
        run: |
          BRANCH_NAME="release/v${{ inputs.version }}"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
      - name: Bump version
        run: |
          python << 'EOF'
          import toml
          
          # Read pyproject.toml
          with open('pyproject.toml', 'r') as f:
              data = toml.load(f)
          
          current_version = data['project']['version']
          new_version = "${{ inputs.version }}"
          
          print(f"Current version: {current_version}")
          print(f"New version: {new_version}")
          
          # Update version
          data['project']['version'] = new_version
          
          # Write back to pyproject.toml
          with open('pyproject.toml', 'w') as f:
              toml.dump(data, f)
          EOF
          
      - name: Commit and push changes
        run: |
          git add pyproject.toml
          git commit -m "chore: bump version to ${{ inputs.version }}"
          git push origin ${{ steps.create_branch.outputs.branch_name }}
          
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ steps.create_branch.outputs.branch_name }} \
            --title "Release v${{ inputs.version }}" \
            --body "This PR bumps the version to ${{ inputs.version }} for release.

          ## Checklist
          - [ ] Version number is correct
          - [ ] All tests are passing
          - [ ] Ready to merge and release
          
          After merging this PR, the build-and-publish job will automatically:
          - Build the package
          - Create a draft GitHub release
          - ${{ inputs.dry_run && 'Skip PyPI publish (dry run)' || 'Publish to PyPI' }}"

  build-and-publish:
    name: Build and Publish
    needs: create-release-pr
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      
    steps:
      - name: Checkout release branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ needs.create-release-pr.outputs.branch_name }}
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.11'
          
      - name: Install uv
        uses: astral-sh/setup-uv@5f42d5af6c403a722299fda36d451c39f302a433 # v4.1.0
          
      - name: Build package
        run: uv build
        
      - name: Generate release notes
        id: release_notes
        run: |
          # Get the previous tag
          PREVIOUS_TAG=$(git tag --sort=-version:refname | head -n 1)
          
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "No previous tag found, showing all commits"
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            echo "Generating release notes from $PREVIOUS_TAG to current"
            COMMITS=$(git log $PREVIOUS_TAG..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi
          
          # Create release notes
          cat << EOF > release_notes.md
          ## What's Changed
          
          $COMMITS
          
          EOF
          
          echo "Release notes generated successfully"
          cat release_notes.md
          
      - name: Create draft GitHub Release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
        with:
          name: v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          body_path: release_notes.md
          files: dist/*
          draft: true
          prerelease: false
          target_commitish: ${{ needs.create-release-pr.outputs.branch_name }}
          
      - name: Publish to PyPI
        if: ${{ !inputs.dry_run }}
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1
        with:
          print-hash: true
